/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as AuthenticatedProfileRouteRouteImport } from './routes/_authenticated/profile/route'
import { Route as authSignupRouteRouteImport } from './routes/(auth)/signup/route'
import { Route as authSigninRouteRouteImport } from './routes/(auth)/signin/route'
import { Route as AuthenticatedLayoutIndexRouteImport } from './routes/_authenticated/_layout/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRouteRoute =
  AuthenticatedProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const authSignupRouteRoute = authSignupRouteRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const authSigninRouteRoute = authSigninRouteRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedLayoutIndexRoute =
  AuthenticatedLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/_layout/': {
      id: '/_authenticated/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRouteImport
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './routes/_authenticated' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated',
    FileRoutesByPath['/_authenticated']['parentRoute'],
    FileRoutesByPath['/_authenticated']['id'],
    FileRoutesByPath['/_authenticated']['path'],
    FileRoutesByPath['/_authenticated']['fullPath']
  >
}
declare module './routes/(auth)/signin/route' {
  const createFileRoute: CreateFileRoute<
    '/(auth)/signin',
    FileRoutesByPath['/(auth)/signin']['parentRoute'],
    FileRoutesByPath['/(auth)/signin']['id'],
    FileRoutesByPath['/(auth)/signin']['path'],
    FileRoutesByPath['/(auth)/signin']['fullPath']
  >
}
declare module './routes/(auth)/signup/route' {
  const createFileRoute: CreateFileRoute<
    '/(auth)/signup',
    FileRoutesByPath['/(auth)/signup']['parentRoute'],
    FileRoutesByPath['/(auth)/signup']['id'],
    FileRoutesByPath['/(auth)/signup']['path'],
    FileRoutesByPath['/(auth)/signup']['fullPath']
  >
}
declare module './routes/_authenticated/profile/route' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/profile',
    FileRoutesByPath['/_authenticated/profile']['parentRoute'],
    FileRoutesByPath['/_authenticated/profile']['id'],
    FileRoutesByPath['/_authenticated/profile']['path'],
    FileRoutesByPath['/_authenticated/profile']['fullPath']
  >
}
declare module './routes/_authenticated/_layout' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/_layout',
    FileRoutesByPath['/_authenticated/_layout']['parentRoute'],
    FileRoutesByPath['/_authenticated/_layout']['id'],
    FileRoutesByPath['/_authenticated/_layout']['path'],
    FileRoutesByPath['/_authenticated/_layout']['fullPath']
  >
}
declare module './routes/_authenticated/_layout/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/_layout/',
    FileRoutesByPath['/_authenticated/_layout/']['parentRoute'],
    FileRoutesByPath['/_authenticated/_layout/']['id'],
    FileRoutesByPath['/_authenticated/_layout/']['path'],
    FileRoutesByPath['/_authenticated/_layout/']['fullPath']
  >
}

// Create and export the route tree

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutIndexRoute: typeof AuthenticatedLayoutIndexRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutIndexRoute: AuthenticatedLayoutIndexRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRouteRoute: typeof AuthenticatedProfileRouteRoute
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRouteRoute: AuthenticatedProfileRouteRoute,
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedLayoutRouteWithChildren
  '/signin': typeof authSigninRouteRoute
  '/signup': typeof authSignupRouteRoute
  '/profile': typeof AuthenticatedProfileRouteRoute
  '/': typeof AuthenticatedLayoutIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/signin': typeof authSigninRouteRoute
  '/signup': typeof authSignupRouteRoute
  '/profile': typeof AuthenticatedProfileRouteRoute
  '/': typeof AuthenticatedLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/signin': typeof authSigninRouteRoute
  '/(auth)/signup': typeof authSignupRouteRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteRoute
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/_layout/': typeof AuthenticatedLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/signin' | '/signup' | '/profile' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/signin' | '/signup' | '/profile' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/_authenticated/profile'
    | '/_authenticated/_layout'
    | '/_authenticated/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authSigninRouteRoute: typeof authSigninRouteRoute
  authSignupRouteRoute: typeof authSignupRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authSigninRouteRoute: authSigninRouteRoute,
  authSignupRouteRoute: authSignupRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/signin",
        "/(auth)/signup"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/profile",
        "/_authenticated/_layout"
      ]
    },
    "/(auth)/signin": {
      "filePath": "(auth)/signin/route.tsx"
    },
    "/(auth)/signup": {
      "filePath": "(auth)/signup/route.tsx"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile/route.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_layout": {
      "filePath": "_authenticated/_layout.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_layout/"
      ]
    },
    "/_authenticated/_layout/": {
      "filePath": "_authenticated/_layout/index.tsx",
      "parent": "/_authenticated/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
