/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities/index'
import { Route as EventsSubmitRouteImport } from './routes/events/submit'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as CommunitiesManagementIndexRouteImport } from './routes/communities/management/index'
import { Route as CommunitiesManagementCreateRouteImport } from './routes/communities/management/create'
import { Route as CommunitiesManagementCommunityIdRouteImport } from './routes/communities/management/$communityId'

// Create/Update Routes

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRoute,
} as any)

const EventsSubmitRoute = EventsSubmitRouteImport.update({
  id: '/events/submit',
  path: '/events/submit',
  getParentRoute: () => rootRoute,
} as any)

const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRoute,
} as any)

const CommunitiesManagementIndexRoute =
  CommunitiesManagementIndexRouteImport.update({
    id: '/communities/management/',
    path: '/communities/management/',
    getParentRoute: () => rootRoute,
  } as any)

const CommunitiesManagementCreateRoute =
  CommunitiesManagementCreateRouteImport.update({
    id: '/communities/management/create',
    path: '/communities/management/create',
    getParentRoute: () => rootRoute,
  } as any)

const CommunitiesManagementCommunityIdRoute =
  CommunitiesManagementCommunityIdRouteImport.update({
    id: '/communities/management/$communityId',
    path: '/communities/management/$communityId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/events/submit': {
      id: '/events/submit'
      path: '/events/submit'
      fullPath: '/events/submit'
      preLoaderRoute: typeof EventsSubmitRouteImport
      parentRoute: typeof rootRoute
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/communities/management/$communityId': {
      id: '/communities/management/$communityId'
      path: '/communities/management/$communityId'
      fullPath: '/communities/management/$communityId'
      preLoaderRoute: typeof CommunitiesManagementCommunityIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/communities/management/create': {
      id: '/communities/management/create'
      path: '/communities/management/create'
      fullPath: '/communities/management/create'
      preLoaderRoute: typeof CommunitiesManagementCreateRouteImport
      parentRoute: typeof rootRoute
    }
    '/communities/management/': {
      id: '/communities/management/'
      path: '/communities/management'
      fullPath: '/communities/management'
      preLoaderRoute: typeof CommunitiesManagementIndexRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/calendar' {
  const createFileRoute: CreateFileRoute<
    '/calendar',
    FileRoutesByPath['/calendar']['parentRoute'],
    FileRoutesByPath['/calendar']['id'],
    FileRoutesByPath['/calendar']['path'],
    FileRoutesByPath['/calendar']['fullPath']
  >
}
declare module './routes/profile' {
  const createFileRoute: CreateFileRoute<
    '/profile',
    FileRoutesByPath['/profile']['parentRoute'],
    FileRoutesByPath['/profile']['id'],
    FileRoutesByPath['/profile']['path'],
    FileRoutesByPath['/profile']['fullPath']
  >
}
declare module './routes/sign-in' {
  const createFileRoute: CreateFileRoute<
    '/sign-in',
    FileRoutesByPath['/sign-in']['parentRoute'],
    FileRoutesByPath['/sign-in']['id'],
    FileRoutesByPath['/sign-in']['path'],
    FileRoutesByPath['/sign-in']['fullPath']
  >
}
declare module './routes/sign-up' {
  const createFileRoute: CreateFileRoute<
    '/sign-up',
    FileRoutesByPath['/sign-up']['parentRoute'],
    FileRoutesByPath['/sign-up']['id'],
    FileRoutesByPath['/sign-up']['path'],
    FileRoutesByPath['/sign-up']['fullPath']
  >
}
declare module './routes/events/$eventId' {
  const createFileRoute: CreateFileRoute<
    '/events/$eventId',
    FileRoutesByPath['/events/$eventId']['parentRoute'],
    FileRoutesByPath['/events/$eventId']['id'],
    FileRoutesByPath['/events/$eventId']['path'],
    FileRoutesByPath['/events/$eventId']['fullPath']
  >
}
declare module './routes/events/submit' {
  const createFileRoute: CreateFileRoute<
    '/events/submit',
    FileRoutesByPath['/events/submit']['parentRoute'],
    FileRoutesByPath['/events/submit']['id'],
    FileRoutesByPath['/events/submit']['path'],
    FileRoutesByPath['/events/submit']['fullPath']
  >
}
declare module './routes/communities/index' {
  const createFileRoute: CreateFileRoute<
    '/communities/',
    FileRoutesByPath['/communities/']['parentRoute'],
    FileRoutesByPath['/communities/']['id'],
    FileRoutesByPath['/communities/']['path'],
    FileRoutesByPath['/communities/']['fullPath']
  >
}
declare module './routes/communities/management/$communityId' {
  const createFileRoute: CreateFileRoute<
    '/communities/management/$communityId',
    FileRoutesByPath['/communities/management/$communityId']['parentRoute'],
    FileRoutesByPath['/communities/management/$communityId']['id'],
    FileRoutesByPath['/communities/management/$communityId']['path'],
    FileRoutesByPath['/communities/management/$communityId']['fullPath']
  >
}
declare module './routes/communities/management/create' {
  const createFileRoute: CreateFileRoute<
    '/communities/management/create',
    FileRoutesByPath['/communities/management/create']['parentRoute'],
    FileRoutesByPath['/communities/management/create']['id'],
    FileRoutesByPath['/communities/management/create']['path'],
    FileRoutesByPath['/communities/management/create']['fullPath']
  >
}
declare module './routes/communities/management/index' {
  const createFileRoute: CreateFileRoute<
    '/communities/management/',
    FileRoutesByPath['/communities/management/']['parentRoute'],
    FileRoutesByPath['/communities/management/']['id'],
    FileRoutesByPath['/communities/management/']['path'],
    FileRoutesByPath['/communities/management/']['fullPath']
  >
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/submit': typeof EventsSubmitRoute
  '/communities': typeof CommunitiesIndexRoute
  '/communities/management/$communityId': typeof CommunitiesManagementCommunityIdRoute
  '/communities/management/create': typeof CommunitiesManagementCreateRoute
  '/communities/management': typeof CommunitiesManagementIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/submit': typeof EventsSubmitRoute
  '/communities': typeof CommunitiesIndexRoute
  '/communities/management/$communityId': typeof CommunitiesManagementCommunityIdRoute
  '/communities/management/create': typeof CommunitiesManagementCreateRoute
  '/communities/management': typeof CommunitiesManagementIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/submit': typeof EventsSubmitRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/communities/management/$communityId': typeof CommunitiesManagementCommunityIdRoute
  '/communities/management/create': typeof CommunitiesManagementCreateRoute
  '/communities/management/': typeof CommunitiesManagementIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/events/$eventId'
    | '/events/submit'
    | '/communities'
    | '/communities/management/$communityId'
    | '/communities/management/create'
    | '/communities/management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/events/$eventId'
    | '/events/submit'
    | '/communities'
    | '/communities/management/$communityId'
    | '/communities/management/create'
    | '/communities/management'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/events/$eventId'
    | '/events/submit'
    | '/communities/'
    | '/communities/management/$communityId'
    | '/communities/management/create'
    | '/communities/management/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsSubmitRoute: typeof EventsSubmitRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  CommunitiesManagementCommunityIdRoute: typeof CommunitiesManagementCommunityIdRoute
  CommunitiesManagementCreateRoute: typeof CommunitiesManagementCreateRoute
  CommunitiesManagementIndexRoute: typeof CommunitiesManagementIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsSubmitRoute: EventsSubmitRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  CommunitiesManagementCommunityIdRoute: CommunitiesManagementCommunityIdRoute,
  CommunitiesManagementCreateRoute: CommunitiesManagementCreateRoute,
  CommunitiesManagementIndexRoute: CommunitiesManagementIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calendar",
        "/profile",
        "/sign-in",
        "/sign-up",
        "/events/$eventId",
        "/events/submit",
        "/communities/",
        "/communities/management/$communityId",
        "/communities/management/create",
        "/communities/management/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/calendar": {
      "filePath": "calendar.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/events/$eventId": {
      "filePath": "events/$eventId.tsx"
    },
    "/events/submit": {
      "filePath": "events/submit.tsx"
    },
    "/communities/": {
      "filePath": "communities/index.tsx"
    },
    "/communities/management/$communityId": {
      "filePath": "communities/management/$communityId.tsx"
    },
    "/communities/management/create": {
      "filePath": "communities/management/create.tsx"
    },
    "/communities/management/": {
      "filePath": "communities/management/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
